Resources:
  # here we define a SSH security group that will be used in the entire company
  MyCompanyWideSSHSecurityGroup:
    # http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH via port 22
      SecurityGroupIngress:
        # we have a lot of rules because it's a perfect security group
        # finance team network
        - IpProtocol: tcp
          CidrIp: 10.0.48.0/24
          FromPort: 22
          ToPort: 22
          # marketing team network
        - IpProtocol: tcp
          CidrIp: 10.0.112.0/24
          FromPort: 22
          ToPort: 22
          # application team support network
        - IpProtocol: tcp
          CidrIp: 10.0.176.0/24
          FromPort: 22
          ToPort: 22

Outputs:
  StackSSHSecurityGroup:
    Description: The SSH Security Group for our company
    Value: !Ref MyCompanyWideSSHSecurityGroup
    Export:
      Name: SSHSecurityGroup
